<?php

namespace EK\PDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FulfillWishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FulfillWishRepository extends EntityRepository
{
}
